openapi: 3.2.0
info:
  title: Veteran and Eligibility Service History API
  description: 'With this API you can

    * Return enrolled benefits for a Veteran.'
  contact:
    name: VA.gov
  version: 2.1.0
servers:
- url: https://sandbox-api.va.gov/services/veteran_verification/{version}
  description: Sandbox
  variables:
    version:
      default: v2
- url: https://api.va.gov/services/veteran_verification/{version}
  description: Production
  variables:
    version:
      default: v2
tags:
- name: Service History
paths:
  /service_history:
    get:
      tags:
      - Service History
      summary: Retrieve the service history of a Veteran
      description: This endpoint provides a Veteran's detailed service history, including all military service episodes with the first and last name of the Veteran, the branch of service, start and end dates, paygrade, discharge status, and separation reason. It also provides start and end dates and locations for each deployment within each episode of service.
      operationId: GET:/service_history
      responses:
        '200':
          description: Service History retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceHistoryResponse'
              example:
                data:
                - id: 2305d238-dee4-5c98-858a-f912e3c059f8
                  type: service-history-episodes
                  attributes:
                    first_name: Jessie
                    last_name: Price
                    branch_of_service: Air Force
                    service_type: Active Duty
                    start_date: '1991-05-29'
                    end_date: '2011-06-30'
                    pay_grade: E07
                    component_of_service: Air Force
                    discharge_status: honorable
                    separation_reason: SUFFICIENT SERVICE FOR RETIREMENT
                    service_episode_combat_pay: false
                    deployments:
                    - start_date: '1948-10-10'
                      end_date: '1949-10-09'
                      location: KOR
                militarySummary:
                  first_name: Jessie
                  last_name: Price
                  active_duty_status: N
                  combat_service_indicator: true
                  duty_status_code: '02'
                  duty_status_text: 'Not on active duty: '
                  total_number_of_regular_active_duty_days: 444
                  total_number_of_reserve_active_duty_days: 90
                  total_number_of_guard_active_duty_days: 60
                  total_number_of_training_days: 10
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              example:
                title: Bad Request
                detail: Bad Request
                code: '400'
                status: '400'
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
              example:
                status: '401'
                error: Invalid Token.
                path: /veteran_verification/v2/service_history
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenServerError'
              example:
                status: '403'
                error: Token not granted requested scope.
                path: /veteran_verification/v2/service_history
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingIcn'
              example:
                title: Veteran not identifiable.
                detail: No data found for ID or demographics.
                code: '404'
                status: '404'
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Request size limit exceeded
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: API rate limit exceeded
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerApiError'
              example:
                title: Internal server error
                detail: Internal server error
                code: '500'
                status: '500'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InaccessibleServiceDefintionErrorApiError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendServiceApiError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: The server took too long to respond
      security:
      - sandboxOauth2:
        - service_history.read
      - productionOauth2:
        - service_history.read
    post:
      tags:
      - Service History
      summary: Retrieve the service history of a Veteran using demographics to search for the…
      description: 'This endpoint provides a Veteran''s detailed service history including all military

        service episodes with the first and last name of the Veteran, the branch of service,

        start and end dates, paygrade, discharge status, and separation reason. It also

        provides start and end dates and locations for each deployment within each episode

        of service.


        Required information:

        * First Name

        * Last Name

        * Date of Birth

        * Street Address

        * City

        * State

        * Country

        * Zipcode


        Optional information:

        * Middle Name

        * Gender


        Tips for finding a match:

        * First and Last Name, Address and DOB are often essential to uniquely identifying a

        Veteran.

        * Home Address is recommended, but it may be beneficial to retry the search with

        additional addresses if they are available and the first attempt is not confirmed.

        * To find a match, it can help to retry with different demographic information,

        such as alternate last names or addresses.

        * It can also help to remove special characters, hyphens, apostrophes, or spaces

        in a name prior to matching.


        NOTE: In the Sandbox only DOB and ZIP are required to identify the test user.'
      operationId: POST:/service_history
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeteranAttributes'
            example:
              first_name: Alfredo
              last_name: Armstrong
              birth_date: '1993-06-08'
              middle_name: M
              gender: M
              street_address_line1: 17020 Tortoise St
              street_address_line2: ''
              street_address_line3: ''
              city: Round Rock
              zipcode: '78664'
              state: TX
              country: USA
        required: true
      responses:
        '200':
          description: Service History retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceHistoryResponse'
              example:
                data:
                - id: 2305d238-dee4-5c98-858a-f912e3c059f8
                  type: service-history-episodes
                  attributes:
                    first_name: Jessie
                    last_name: Price
                    branch_of_service: Air Force
                    service_type: Active Duty
                    start_date: '1991-05-29'
                    end_date: '2011-06-30'
                    pay_grade: E07
                    component_of_service: Air Force
                    discharge_status: honorable
                    separation_reason: SUFFICIENT SERVICE FOR RETIREMENT
                    service_episode_combat_pay: false
                    deployments:
                    - start_date: '1948-10-10'
                      end_date: '1949-10-09'
                      location: KOR
                militarySummary:
                  first_name: Jessie
                  last_name: Price
                  active_duty_status: N
                  combat_service_indicator: true
                  duty_status_code: '02'
                  duty_status_text: 'Not on active duty: '
                  total_number_of_regular_active_duty_days: 444
                  total_number_of_reserve_active_duty_days: 90
                  total_number_of_guard_active_duty_days: 60
                  total_number_of_training_days: 10
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              example:
                title: Bad Request
                detail: Bad Request
                code: '400'
                status: '400'
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
              example:
                status: '401'
                error: Invalid Token.
                path: /veteran_verification/v2/service_history
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenServerError'
              example:
                status: '403'
                error: Token not granted requested scope.
                path: /veteran_verification/v2/service_history
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingIcn'
              example:
                title: Veteran not identifiable.
                detail: No data found for ID or demographics.
                code: '404'
                status: '404'
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Request size limit exceeded
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: API rate limit exceeded
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerApiError'
              example:
                title: Internal server error
                detail: Internal server error
                code: '500'
                status: '500'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InaccessibleServiceDefintionErrorApiError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendServiceApiError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: The server took too long to respond
      security:
      - sandboxOauth2:
        - service_history.read
      - productionOauth2:
        - service_history.read
components:
  schemas:
    Deployment:
      required:
      - end_date
      - location
      - start_date
      type: object
      properties:
        start_date:
          type:
          - string
          - 'null'
          description: beginning of deployment (YYYY-mm-dd)
          format: date
          example: '1948-10-10'
        end_date:
          type:
          - string
          - 'null'
          description: end of deployment (YYYY-mm-dd)
          format: date
          example: '1949-10-09'
        location:
          type:
          - string
          - 'null'
          description: Three letter ISO country code of deployment location
          example: KOR
      description: Deployment during a service history episode
      deprecated: true
    AuthorizationError:
      type: object
      properties:
        status:
          type: string
          example: '401'
        error:
          type: string
          example: Invalid token.
        path:
          type: string
          example: /veteran_verification/v2/{endpoint}
    ServiceHistoryAttributes:
      required:
      - branch_of_service
      - component_of_service
      - discharge_status
      - end_date
      - first_name
      - last_name
      - pay_grade
      - separation_reason
      - service_episode_combat_pay
      - service_type
      - start_date
      type: object
      properties:
        deployments:
          type: array
          items:
            $ref: '#/components/schemas/Deployment'
        first_name:
          type:
          - string
          - 'null'
          description: Veteran first name
          example: Abraham
        last_name:
          type:
          - string
          - 'null'
          description: Veteran last name
          example: Lincoln
        branch_of_service:
          type: string
          description: The branch of service such as National Guard, Coast Guard, Reserves, Army, Navy, Air Force, Marines
          example: Army
        component_of_service:
          type: string
          description: A component of service such as Reserves, National Guard
          example: Reserves
        service_type:
          type: string
          description: If veteran is on active duty or not
          example: Active Duty
        start_date:
          type:
          - string
          - 'null'
          description: start date of a service history episode (YYYY-mm-dd)
          format: date
          example: '1948-04-08'
        end_date:
          type:
          - string
          - 'null'
          description: end date of a service history episode (YYYY-mm-dd)
          format: date
          example: '1950-05-10'
        pay_grade:
          type: string
          description: "Defines the level of compensation for a position, normalized across military branches.\n\nPossible values include the concatenation of Pay Plan Code and Pay Grade Code.\nPay Plan Code is represented as a two-character code, and can be one of five values:\n  - CC (Commissioned Corps)\n  - MC (Cadet)\n  - ME (Enlisted)\n  - MO (Officer)\n  - MW (Warrant Officer)\n\nPay Grade Code is a value between 01 and 10.\n\nPay Plan Code is concatenated with Pay Grade Code to determine the full Pay Grade value, with the leading character (M or C) stripped from Pay Plan Code."
          example: W01
        discharge_status:
          type:
          - string
          - 'null'
          description: 'Character of discharge from service episode. Possible values are:


            Both "honorable-for-va-purposes" and "dishonorable-for-va-purposes" represent a change in character of discharge based on an administrative decision, for purposes of VA benefits administration. The original character of discharge for other purposes was either "bad-conduct" or "other-than-honorable". "honorable-absence-of-negative-report" represents an unreported character of service that the Department of Defense classifies as honorable.'
          example: HONORABLE
          enum:
          - honorable
          - general
          - bad-conduct
          - other-than-honorable
          - dishonorable
          - honorable-absence-of-negative-report
          - honorable-for-va-purposes
          - dishonorable-for-va-purposes
          - uncharacterized
          - unknown
        separation_reason:
          type: string
          description: Additional text description for separation reason beyond discharge_status value
          example: SUFFICIENT SERVICE FOR RETIREMENT
        service_episode_combat_pay:
          type:
          - boolean
          - 'null'
          description: If there is any record of combat pay for a Veteran's service period, return "true."
          example: false
      description: Attributes for service_history endpoint
    InaccessibleServiceDefintionErrorApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Bad Gateway
          detail: Upstream Request Error.
          code: '502'
          status: '502'
    VeteranAttributes:
      required:
      - birth_date
      - city
      - country
      - first_name
      - last_name
      - street_address_line1
      - zipcode
      type: object
      properties:
        gender:
          type: string
          description: For gender, only 'm' or 'f' will help the search currently.
        first_name:
          type: string
          description: '* Some names may require special handling if a Veteran is not found.

            * Try removing special characters, such as hyphens, apostrophes, and spaces prior to

            matching. For example, a submission of ''De''Anna'' can be matched as ''deanna''.

            * In addition, depending on the handling logic of the front end application updating the VA

            record, an inquiry with first name of ''Ann-Marie'' would be standardized to ''AnnMarie'' but

            could be matched against ''AnnMarie'' or ''Ann Marie'' or ''Ann'' or ''Marie''.

            * Therefore, if a Veteran with a hyphenated name is not found, it may be useful to retry the

            hyphenated name without the hyphen and together, then separated, then each individual part

            of the name as in the example with ''Ann-Marie''.

            * Capitalization does not impede match strength.

            '
        middle_name:
          type: string
        last_name:
          type: string
          description: '* Some names may require special handling if a Veteran is not found.

            * Try removing special characters, such as hyphens, apostrophes, and spaces prior to

            matching. For example, a submission of ''O''leary'' can be matched as ''oleary''.

            * In addition, depending on the handling logic of the front end application updating the

            VA record, an inquiry with last name of ''Smith-Jones'' would be standardized to

            ''SmithJones'' but could be matched against ''SmithJones'' or ''Smith Jones'' or ''Smith'' or

            ''Jones''.

            * Therefore, if a Veteran with a hyphenated name is not found, it may be useful to retry

            the hyphenated name without the hyphen and together, then separated, then each

            individual part of the name as in the example with ''Smith-Jones''.

            * Capitalization does not impede match strength.'
        zipcode:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        birth_date:
          type: string
          format: date
        street_address_line1:
          type: string
          description: 'Address line 1 can accept one or more letters (uppercase or

            lowercase), digits, spaces, commas, hashes(#), apostrophes(''),

            periods(.), back slashes(\\), forward slashes(/), or hyphens(-).

            '
        street_address_line2:
          type: string
          description: 'Address line 2 can accept one or more letters (uppercase or

            lowercase), digits, spaces, commas, hashes(#), apostrophes(''),

            periods(.), back slashes(\\), forward slashes(/), or hyphens(-).

            '
        street_address_line3:
          type: string
          description: 'Address line 3 can accept one or more letters (uppercase or

            lowercase), digits, spaces, commas, hashes(#), apostrophes(''),

            periods(.), back slashes(\\), forward slashes(/), or hyphens(-).

            '
        home_phone_number:
          type: string
        birth_place_city:
          type: string
        birth_place_state:
          type: string
        birth_place_country:
          type: string
        mothers_maiden_name:
          type: string
      description: '* Use the current residence address of the Veteran.

        * Some unhoused Veterans can use a local USPS, support organization, or other location

        such as ''the corner of RTE512 and U.S.1''.

        * Aim to match the input against the Veteran''s demographic information in their VA.gov

        profile.

        * Data in the request and the VA record is standardized using the same algorithm prior

        to matching. If the data is close, and enough fields are provided, it will find the

        Veteran most of the time; however, some records will have data that is not in sync and

        may require trying the request again with different addresses, names, or formats.

        * Alternately, the Veteran may need to update their information with the VA if they

        are not found.

        '
    InternalServerApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Internal server error
          detail: Internal server error
          code: '500'
          status: '500'
    ServiceHistoryMilitarySummary:
      required:
      - active_duty_status
      - combat_service_indicator
      - duty_status_code
      - duty_status_text
      - first_name
      - last_name
      - total_number_of_guard_active_duty_days
      - total_number_of_regular_active_duty_days
      - total_number_of_reserve_active_duty_days
      - total_number_of_training_days
      type: object
      properties:
        first_name:
          type:
          - string
          - 'null'
          description: Veteran first name
          example: Abraham
        last_name:
          type:
          - string
          - 'null'
          description: Veteran last name
          example: Lincoln
        active_duty_status:
          type:
          - string
          - 'null'
          description: Indicates the Veteran's current active duty status
          example: 'false'
        combat_service_indicator:
          type:
          - boolean
          - 'null'
          description: Indicates whether the service member has ever been a part of active combat duty
          example: false
        duty_status_code:
          type:
          - string
          - 'null'
          description: Describes the individual's status
          example: A
        duty_status_text:
          type:
          - string
          - 'null'
          description: Relates to an individual's affiliation with the US Military.
          example: Active Component = full time active duty, not in the Guard or Reserve
        total_number_of_regular_active_duty_days:
          type:
          - integer
          - 'null'
          description: Total number of regular active duty days
          format: int32
          example: 100
        total_number_of_reserve_active_duty_days:
          type:
          - integer
          - 'null'
          description: Total number of reserve active duty days
          format: int32
          example: 100
        total_number_of_guard_active_duty_days:
          type:
          - integer
          - 'null'
          description: Total number of guard active duty days
          format: int32
          example: 100
        total_number_of_training_days:
          type:
          - integer
          - 'null'
          description: Total number of training days
          format: int32
          example: 100
      description: Military Summary for Veteran
    ServiceHistoryResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ServiceHistoryEpisode'
        military_summary:
          $ref: '#/components/schemas/ServiceHistoryMilitarySummary'
      description: verification service_history endpoint
      deprecated: true
    ForbiddenServerError:
      type: object
      properties:
        status:
          type: string
          example: '403'
        error:
          type: string
          example: Token not granted requested scope.
        path:
          type: string
          example: /veteran_verification/v2/{endpoint}
    ApiErrorDetails:
      type: object
      properties:
        title:
          type: string
          example: Error title
        detail:
          type: string
          example: Detailed error message
        code:
          type: string
          example: Error Code
        status:
          type: string
          example: Error Code
    BadRequest:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Bad Request
          detail: Bad Request
          code: '400'
          status: '400'
    BackendServiceApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Service Unavailable
          detail: Backend Service Unavailable.
          code: '503'
          status: '503'
    MissingIcn:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Veteran not identifiable.
          detail: No data found for ID or demographics.
          code: '404'
          status: '404'
    ServiceHistoryEpisode:
      required:
      - attributes
      - id
      - type
      type: object
      properties:
        id:
          type: string
          description: Service History Episode ID
          example: 12312AASDf
        type:
          type: string
          example: service-history-episodes
        attributes:
          $ref: '#/components/schemas/ServiceHistoryAttributes'
      description: Service history for authorized Veteran
  securitySchemes:
    productionOauth2:
      type: oauth2
      description: This API uses OAuth 2.0 with client credentials grant flow and authorization code grant flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            disability_rating_summary_restricted.read: For approved federal consumers, view a Veteran's VA disability rating summary using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            launch.read: Retrieve Launch
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            permanent_and_total_disability_restricted.read: 'Vew a Veteran''s P&T and IU disability statuses and effective dates, based on restricted user attributes. '
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
        authorizationCode:
          authorizationUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/authorization
          tokenUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
    sandboxOauth2:
      type: oauth2
      description: This API uses OAuth 2.0 with client credentials grant flow and authorization code grant flow
      flows:
        clientCredentials:
          tokenUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            disability_rating_summary_restricted.read: For approved federal consumers, view a Veteran's VA disability rating summary using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            launch.read: Retrieve Launch
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            permanent_and_total_disability_restricted.read: 'Vew a Veteran''s P&T and IU disability statuses and effective dates, based on restricted user attributes. '
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
        authorizationCode:
          authorizationUrl: https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/authorization
          tokenUrl: https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
