openapi: 3.2.0
info:
  title: Veteran Service History and Eligibility Enrolled Benefits…
  description: 'With this API you can

    * Return enrolled benefits for a Veteran.'
  contact:
    name: VA.gov
  version: 2.1.0
servers:
- url: https://sandbox-api.va.gov/services/veteran_verification/{version}
  description: Sandbox
  variables:
    version:
      default: v2
- url: https://api.va.gov/services/veteran_verification/{version}
  description: Production
  variables:
    version:
      default: v2
tags:
- name: Enrolled Benefits
paths:
  /enrolled_benefits:
    get:
      tags:
      - Enrolled Benefits
      summary: Get enrolled benefits information
      description: 'This endpoint returns select enrolled benefits for a Veteran.

        If the Veteran is enrolled, the codes and names for benefits they are

        receiving will be returned for the following benefit types:


        * Compensation (Code C)

        * 306 Pension (Code 306P)

        * Old Law Pension (Code OLP)

        * Improved Pension (Code IP)'
      operationId: GET:/enrolled_benefits
      responses:
        '200':
          description: Enrolled benefits successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeteranEnrolledBenefitsConfirmation'
              example:
                veteran_benefits:
                - program_code: C
                  program_name: ''
                  award_effective_date: '2022-01-11T00:00:00Z'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              example:
                title: Bad Request
                detail: Bad Request
                code: '400'
                path: /veteran_verification/v2/enrolled_benefits
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
              example:
                status: '401'
                error: Invalid Token.
                path: /veteran_verification/v2/enrolled_benefits
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenServerError'
              example:
                status: '403'
                error: Token not granted requested scope.
                path: /veteran_verification/v2/enrolled_benefits
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingIcn'
              example:
                title: Veteran not identifiable.
                detail: No data found for ID or demographics.
                code: '404'
                status: '404'
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Request size limit exceeded
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: API rate limit exceeded
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerApiError'
              example:
                title: Internal server error
                detail: Internal server error
                code: '500'
                status: '500'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InaccessibleServiceDefintionErrorApiError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendServiceApiError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: The server took too long to respond
      security:
      - sandboxOauth2:
        - enrolled_benefits.read
      - productionOauth2:
        - enrolled_benefits.read
    post:
      tags:
      - Enrolled Benefits
      summary: Get enrolled benefits information using demographics to search for the Veteran
      description: 'This endpoint returns select enrolled benefits for a Veteran.

        If the Veteran is enrolled, the codes and names for benefits they are

        receiving will be returned for the following benefit types:


        * Compensation (Code C)

        * 306 Pension (Code 306P)

        * Old Law Pension (Code OLP)

        * Improved Pension (Code IP)


        Required information:

        * First Name

        * Last Name

        * Date of Birth

        * Street Address

        * City

        * State

        * Country

        * Zipcode


        Optional information:

        * Middle Name

        * Gender


        Tips for finding a match:


        * First and Last Name, Address and DOB are often essential to uniquely identifying

        a Veteran.

        * Home Address is recommended, but it may be beneficial to retry the search with

        additional addresses if they are available and the first attempt is not confirmed.

        * To find a match, it can help to retry with different demographic information, such

        as alternate last names or addresses.

        * It can also help to remove special characters, hyphens, apostrophes, or spaces in

        a name prior to matching.


        NOTE: In the Sandbox only DOB and ZIP are required to identify the test user.'
      operationId: POST:/enrolled_benefits
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeteranAttributes'
            example:
              first_name: Alfredo
              last_name: Armstrong
              birth_date: '1993-06-08'
              middle_name: M
              gender: M
              street_address_line1: 17020 Tortoise St
              street_address_line2: ''
              street_address_line3: ''
              city: Round Rock
              zipcode: '78664'
              state: TX
              country: USA
        required: true
      responses:
        '200':
          description: Enrolled benefits successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VeteranEnrolledBenefitsConfirmation'
              example:
                veteran_benefits:
                - program_code: C
                  program_name: ''
                  award_effective_date: '2022-01-11T00:00:00Z'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
              example:
                title: Bad Request
                detail: Bad Request
                code: '400'
                status: '400'
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'
              example:
                status: '401'
                error: Invalid Token.
                path: /veteran_verification/v2/enrolled_benefits
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenServerError'
              example:
                status: '403'
                error: Token not granted requested scope.
                path: /veteran_verification/v2/enrolled_benefits
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingIcn'
              example:
                title: Veteran not identifiable.
                detail: No data found for ID or demographics.
                code: '404'
                status: '404'
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Request size limit exceeded
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: API rate limit exceeded
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerApiError'
              example:
                title: Internal server error
                detail: Internal server error
                code: '500'
                status: '500'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InaccessibleServiceDefintionErrorApiError'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackendServiceApiError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: The server took too long to respond
      security:
      - sandboxOauth2:
        - enrolled_benefits.read
      - productionOauth2:
        - enrolled_benefits.read
components:
  schemas:
    AuthorizationError:
      type: object
      properties:
        status:
          type: string
          example: '401'
        error:
          type: string
          example: Invalid token.
        path:
          type: string
          example: /veteran_verification/v2/{endpoint}
    InaccessibleServiceDefintionErrorApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Bad Gateway
          detail: Upstream Request Error.
          code: '502'
          status: '502'
    VeteranAttributes:
      required:
      - birth_date
      - city
      - country
      - first_name
      - last_name
      - street_address_line1
      - zipcode
      type: object
      properties:
        gender:
          type: string
          description: For gender, only 'm' or 'f' will help the search currently.
        first_name:
          type: string
          description: '* Some names may require special handling if a Veteran is not found.

            * Try removing special characters, such as hyphens, apostrophes, and spaces prior to

            matching. For example, a submission of ''De''Anna'' can be matched as ''deanna''.

            * In addition, depending on the handling logic of the front end application updating the VA

            record, an inquiry with first name of ''Ann-Marie'' would be standardized to ''AnnMarie'' but

            could be matched against ''AnnMarie'' or ''Ann Marie'' or ''Ann'' or ''Marie''.

            * Therefore, if a Veteran with a hyphenated name is not found, it may be useful to retry the

            hyphenated name without the hyphen and together, then separated, then each individual part

            of the name as in the example with ''Ann-Marie''.

            * Capitalization does not impede match strength.

            '
        middle_name:
          type: string
        last_name:
          type: string
          description: '* Some names may require special handling if a Veteran is not found.

            * Try removing special characters, such as hyphens, apostrophes, and spaces prior to

            matching. For example, a submission of ''O''leary'' can be matched as ''oleary''.

            * In addition, depending on the handling logic of the front end application updating the

            VA record, an inquiry with last name of ''Smith-Jones'' would be standardized to

            ''SmithJones'' but could be matched against ''SmithJones'' or ''Smith Jones'' or ''Smith'' or

            ''Jones''.

            * Therefore, if a Veteran with a hyphenated name is not found, it may be useful to retry

            the hyphenated name without the hyphen and together, then separated, then each

            individual part of the name as in the example with ''Smith-Jones''.

            * Capitalization does not impede match strength.'
        zipcode:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        birth_date:
          type: string
          format: date
        street_address_line1:
          type: string
          description: 'Address line 1 can accept one or more letters (uppercase or

            lowercase), digits, spaces, commas, hashes(#), apostrophes(''),

            periods(.), back slashes(\\), forward slashes(/), or hyphens(-).

            '
        street_address_line2:
          type: string
          description: 'Address line 2 can accept one or more letters (uppercase or

            lowercase), digits, spaces, commas, hashes(#), apostrophes(''),

            periods(.), back slashes(\\), forward slashes(/), or hyphens(-).

            '
        street_address_line3:
          type: string
          description: 'Address line 3 can accept one or more letters (uppercase or

            lowercase), digits, spaces, commas, hashes(#), apostrophes(''),

            periods(.), back slashes(\\), forward slashes(/), or hyphens(-).

            '
        home_phone_number:
          type: string
        birth_place_city:
          type: string
        birth_place_state:
          type: string
        birth_place_country:
          type: string
        mothers_maiden_name:
          type: string
      description: '* Use the current residence address of the Veteran.

        * Some unhoused Veterans can use a local USPS, support organization, or other location

        such as ''the corner of RTE512 and U.S.1''.

        * Aim to match the input against the Veteran''s demographic information in their VA.gov

        profile.

        * Data in the request and the VA record is standardized using the same algorithm prior

        to matching. If the data is close, and enough fields are provided, it will find the

        Veteran most of the time; however, some records will have data that is not in sync and

        may require trying the request again with different addresses, names, or formats.

        * Alternately, the Veteran may need to update their information with the VA if they

        are not found.

        '
    InternalServerApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Internal server error
          detail: Internal server error
          code: '500'
          status: '500'
    ForbiddenServerError:
      type: object
      properties:
        status:
          type: string
          example: '403'
        error:
          type: string
          example: Token not granted requested scope.
        path:
          type: string
          example: /veteran_verification/v2/{endpoint}
    ApiErrorDetails:
      type: object
      properties:
        title:
          type: string
          example: Error title
        detail:
          type: string
          example: Detailed error message
        code:
          type: string
          example: Error Code
        status:
          type: string
          example: Error Code
    BackendServiceApiError:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Service Unavailable
          detail: Backend Service Unavailable.
          code: '503'
          status: '503'
    VeteranEnrolledBenefitsConfirmation:
      type: object
      properties:
        veteran_benefits:
          type: array
          description: Array of Veteran enrolled benefits for an individual
          items:
            $ref: '#/components/schemas/VeteranEnrolledBenefit'
      description: Veteran enrolled benefits for an individual
    BadRequest:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Bad Request
          detail: Bad Request
          code: '400'
          status: '400'
    MissingIcn:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorDetails'
      example:
        errors:
        - title: Veteran not identifiable.
          detail: No data found for ID or demographics.
          code: '404'
          status: '404'
    VeteranEnrolledBenefit:
      required:
      - program_code
      type: object
      properties:
        program_code:
          type: string
          description: The program identifier
        program_name:
          type: string
          description: The human readable program name
        award_effective_date:
          type: string
          format: date-time
      description: Individual Veteran enrolled benefit
  securitySchemes:
    productionOauth2:
      type: oauth2
      description: This API uses OAuth 2.0 with client credentials grant flow and authorization code grant flow.
      flows:
        clientCredentials:
          tokenUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            disability_rating_summary_restricted.read: For approved federal consumers, view a Veteran's VA disability rating summary using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            launch.read: Retrieve Launch
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            permanent_and_total_disability_restricted.read: 'Vew a Veteran''s P&T and IU disability statuses and effective dates, based on restricted user attributes. '
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
        authorizationCode:
          authorizationUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/authorization
          tokenUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
    sandboxOauth2:
      type: oauth2
      description: This API uses OAuth 2.0 with client credentials grant flow and authorization code grant flow
      flows:
        clientCredentials:
          tokenUrl: https://api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            disability_rating_summary_restricted.read: For approved federal consumers, view a Veteran's VA disability rating summary using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            launch.read: Retrieve Launch
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            permanent_and_total_disability_restricted.read: 'Vew a Veteran''s P&T and IU disability statuses and effective dates, based on restricted user attributes. '
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
        authorizationCode:
          authorizationUrl: https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/authorization
          tokenUrl: https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/token
          scopes:
            aca_coverage_restricted.read: Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).
            disability_rating.read: Retrieve Disability Rating
            disability_rating_summary.read: Retrieve Disability Rating Summary
            disability_rating_restricted.read: For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.
            enrolled_benefits.read: Retrieve Veteran Enrolled Benefits
            flashes.read: Retrieve Flashes
            permanent_and_total_disability.read: View a Veteran's P&T and IU disability statuses and effective dates.
            service_history.read: Retrieve Service History
            status_restricted.read: For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.
            veteran_status.read: Retrieve Veteran Status
